### ISSUE TITLE
Can't import rotor::Time

### ISSUE THREAD

**Issue by code-ape** [tailhook/rotor#16]
Importing `rotor::Time` fails with:

```
src/main.rs:3:5: 3:16 error: unresolved import `rotor::Time`. There is no `Time` in `rotor` [E0432]
src/main.rs:3 use rotor::Time;
```

I am using needing to use it because I am attempting to run the [rotor-http example](https://github.com/tailhook/rotor-http/blob/master/examples/hello_world_server.rs). I have no idea why this isn't working. I have rotor 0.5.1 and am using rustc 1.8.0-nightly (57c357d89 2016-02-16).

Any ideas?

**Comment by code-ape** [comment]
Found the problem! I see your published libraries aren't quite up to date. Solved with:

```
rotor = {git="git://github.com/tailhook/rotor", rev="08946ce"}
rotor-http = {git="git://github.com/tailhook/rotor-http", rev="3e75466"}
```

I will leave this up to you to close depending on whether or not you see this as a serious issue.

**Comment by tailhook** [comment]
Well, it looks like you need the dependencies from git when using an example from git.

Hopefully, we'll get a new release of rotor (and all the ecosystem) soon. And hopefully API is mostly mature, so it should not break too much in the future.
