### ISSUE TITLE
Shutdown on last machine closing?

### ISSUE THREAD

**Issue by partim** [tailhook/rotor#20]
This may just be me trying to find the easy way out for closing down a complex setup of multiple machines, but would it make sense to let the loop instance shut itself down when the last machine has closed? Naively, I would think that in this case the loop is hanging with no way out, anyway.

**Comment by tailhook** [comment]
Yes, it makes sense. We should probably implement that. (Would you like to make a PR?)

This may be not so useful as you might think, though. For servers, you always have a listening socket. And even if you close it, clients may be hanging arbitrarily long. For clients, you will probably have a DNS resolver as a separate state machine, which probably never shuts down.

**Comment by partim** [comment]
I'll look into making a PR.

Incidentally, I have a DNS state machine in a separate thread (it does TCP and will do (D)TLS later so there is lots of machines) and I want it to shut down when the last user-side resolver is dropped. (For reference: https://github.com/cloudshipping/domain).

The server example is a good one, too, though: For a clean shutdown, you want to give all pending connections a chance to terminate whatever protocol their are doing and then close. So informing all machines of a pending shutdown, let them close on their own, and just wait for `run()` to return seems a fairly pretty way of doing this.

**Comment by tailhook** [comment]
> Incidentally, I have a DNS state machine in a separate thread (it does TCP and will do (D)TLS later so there is lots of machines) and I want it to shut down when the last user-side resolver is dropped. (For reference: https://github.com/cloudshipping/domain).

Any specific reason you are running it in separate thread? I don't think TCP and DTLS are too CPU-intensive so you need offloading of the work. Or do you make a DNS library for synchronous code?

(BTW, any thoughts on how we could join the effort on DNS? I'm writing a rotor-dns, dns-parser and resolv-conf parser crates, which looks like you're reimplementing too)

**Comment by partim** [comment]
> Any specific reason you are running it in separate thread? I don't think TCP and DTLS are too CPU-intensive so you need offloading of the work. Or do you make a DNS library for synchronous code?

The separate thread is for synchronous code, indeed. But you can also get a `rotor::Machine` for composition.

> (BTW, any thoughts on how we could join the effort on DNS? I'm writing a rotor-dns, dns-parser and resolv-conf parser crates, which looks like you're reimplementing too)

I could start with adding some architectural documentation to make it easier to judge the design. Our approaches are quite different, both in the wire parsing and the resolver, that it might be worthwhile to explore both a little further? Part of the goal of writing the resolver and, next, a simple authoritative name server is to determine whether my approach to wire parsing and composing is actually practical.

**Comment by tailhook** [comment]
> Our approaches are quite different, both in the wire parsing and the resolver, that it might be worthwhile to explore both a little further?

Sure, feel free to open an issue in any of the projects if you think my design is suboptimal. Don't take me wrong, I have no goal of owning of the DNS implementation. What I'm interested in, is standard async implementation of DNS for rust/rotor, which is universal enough for most users. If it would be yours it's fine.

On the other hand there is the evindence (https://github.com/tailhook/dns-parser/issues/3#issuecomment-216868795, bottom of the comment) that dns-parser crate is useful beyond resolver, so splitting it is useful.

(I'll look at the pull request later tonight, need some time to test it)

**Comment by partim** [comment]
> Sure, feel free to open an issue in any of the projects if you think my design is suboptimal.

I wouldn’t want to judge either approach at this point. I think it takes a bunch of more use cases to see which approach is better.

> Don't take me wrong, I have no goal of owning of the DNS implementation. What I'm interested in, is standard async implementation of DNS for rust/rotor, which is universal enough for most users. If it would be yours it's fine.

Same here, really. Although I do think there is room for more than one implementation since there is differing requirements. My goal is more a complete library akin to ldns, getdns, or libunbound. That might be overkill for a standard resolver for, say, a web service.
