### ISSUE TITLE
Want to be on Rusty Radio?

### ISSUE THREAD

**Issue by Hoverbear** [tailhook/rotor#8]
Hey!

First, super sorry for making this an issue, I couldn't find a public email for you (@tailhook) so this was the next best option.

I wanted to reach out to you about being a part of an episode of Rusty Radio! My good friend @posix4e is the host and we've gotten requests to hear more about you and about Rotor! We've both enjoyed the blog posts about how it works.

If you're interested please reach out to me (andrew@hoverbear.org) and we'll get @posix4e looped into the conversation about when works best for you. The entire process should take maybe 45 minutes including getting the audio working.

All the best! Feel free to close this issue at any time.

**Comment by posix4e** [comment]
+-
On Fri, Jan 22, 2016 at 10:04 AM Andrew Hobden notifications@github.com
wrote:

> Hey!
> 
> First, super sorry for making this an issue, I couldn't find a public
> email for you (@tailhook https://github.com/tailhook) so this was the
> next best option.
> 
> I wanted to reach out to you about being a part of an episode of Rusty
> Radio! My good friend @posix4e https://github.com/posix4e is the host
> and we've gotten requests to hear more about you and about Rotor! We've
> both enjoyed the blog posts about how it works.
> 
> If you're interested please reach out to me (andrew@hoverbear.org) and
> we'll get @posix4e https://github.com/posix4e looped into the
> conversation about when works best for you. The entire process should take
> maybe 45 minutes including getting the audio working.
> 
> All the best! Feel free to close this issue at any time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tailhook/rotor/issues/8.
> 
> ## 

Sent from my mobile 5045076749
Alex Newman

**Comment by posix4e** [comment]
Err +1
On Fri, Jan 22, 2016 at 7:11 PM Alex Newman posix4e@gmail.com wrote:

> +-
> On Fri, Jan 22, 2016 at 10:04 AM Andrew Hobden notifications@github.com
> wrote:
> 
> > Hey!
> > 
> > First, super sorry for making this an issue, I couldn't find a public
> > email for you (@tailhook https://github.com/tailhook) so this was the
> > next best option.
> > 
> > I wanted to reach out to you about being a part of an episode of Rusty
> > Radio! My good friend @posix4e https://github.com/posix4e is the host
> > and we've gotten requests to hear more about you and about Rotor! We've
> > both enjoyed the blog posts about how it works.
> > 
> > If you're interested please reach out to me (andrew@hoverbear.org) and
> > we'll get @posix4e https://github.com/posix4e looped into the
> > conversation about when works best for you. The entire process should take
> > maybe 45 minutes including getting the audio working.
> > 
> > All the best! Feel free to close this issue at any time.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/tailhook/rotor/issues/8.
> > 
> > ## 
> 
> Sent from my mobile 5045076749
> Alex Newman
> 
> ## 

Sent from my mobile 5045076749
Alex Newman

**Comment by tailhook** [comment]
Well, you can always find my email in the git log :) Anyway, opening the issue is perfectly okay, no need to apologize. I've mailed you.
